language: java
dist: trusty
env:
  global:
    -CODECOV_TOKEN=2444f1ed-df13-4323-b41e-7ce2bc11bf15
  secure: "kjedkquOni8VqXnPnvKdusDK4p8plYYaL0rdb2/PEb58DcVatkwpF4KxafbSFCOtCOPZIq92dJeqLnlgyqNi2P66fqaicSzi+9LTCoX9wizwg5EGpFpV7E12YpvvVnOvPe8mTURRHgvgy+1zJ1KYFvua182XbuSGAEwubrJDKBLCBkZ0vHJGXJcEeD8qH3q146LDj2Dt2jaMGyS2myjHz11wRzNHDAd2Yhbz5j2jtAh8C+ugqVxRdnNjenA+j66u+3CS4Cji0zFxjUUC3Bx5QqBY0/JM9OlE5LqNJ7jnSQBTDTABY7KLV7aLQBSTE24Bj9tLEpdlapilDvlOx4fvxQ+CRD9Qz6C9Ogl/CdBUrxk2XxugDyt8DGjh6ZkBxQC4LbNXbMFbmr3CqlFYpOYZOd/OoG4WsB6Ka7TzH25jCsiVYZ3ubmkbRiLaZXgkXwVQLon4SzX7AzP48TUlC9zL8lmcu2cGmUi4Dk5Yo2Dq90AaKuJ5vscMZWcuKK+PBm79EkVCREP7gQvQmM+Ic24ONZhduNnlycoC4cdJiF4B/WVOZ2Ug9+qJXkmBxt1nxaoXDmprxGGrv3RVuYmNTr92hOMPJrHK+RH5BRDzV5F1vo3+IQZQ121JzxjTkbm1t/jomTayeF7Aa2nJh+K7IjfsHyH1P7V55l7VgQVCptW1+Xs="
jdk:
  - oraclejdk8
  - openjdk8
before_install:
  - "sh travis/copy_settings.sh"
after_success:
  - mvn jacoco:report coveralls:report
  - bash <(curl -s https://codecov.io/bash)
