language: java
dist: trusty
jdk:
  - oraclejdk8
    # - openjdk8
    # - oraclejdk9
    # - openjdk9
    # - openjdk10
    # - oraclejdk11
    # - openjdk11
    # - oraclejdk12
    # - openjdk12
    # - oraclejdk13
    # - openjdk13
before_install:
  - openssl aes-256-cbc -K $encrypted_d894207b50dc_key -iv $encrypted_d894207b50dc_iv
    -in travis/libraries-key.asc.enc -out travis/libraries-key.asc -d
  - gpg --import travis/libraries-key.asc
  - sh travis/copy_maven_settings.sh
jobs:
  include:
    - stage: "Reporting tests for Coveralls"
      install: skip
      script: travis/coveralls.sh
      jdk: openjdk8    
deploy:
  - provider: script
    script: travis/deploy.sh
    on:
      condition: $TRAVIS_BRANCH =~ ^(develop|master)$
      condition: ./travis/check_deploy_version.sh
      branch: develop 
      jdk: openjdk8
