language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9
  - openjdk10
  - oraclejdk11
  - openjdk11
  - oraclejdk12
  - openjdk12
  - oraclejdk13
  - openjdk13
before_install:
  - sh travis/import_gpg_key.sh
  - sh travis/copy_maven_settings.sh
jobs:
  include:
    - stage: "Coveralls report"
      if: NOT type = pull_request
      install: skip
      script: travis/coveralls.sh
      jdk: openjdk8    
    - stage: "Snapshot deploy"
      if: branch = develop AND NOT type = pull_request
      install: skip
      script: travis/deploy/deploy_snapshot.sh
      jdk: openjdk8
    - stage: "Release deploy"
      if: branch = master AND NOT type = pull_request
      install: skip
      script: travis/deploy/deploy_release.sh
      jdk: openjdk8
