language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_d894207b50dc_key -iv $encrypted_d894207b50dc_iv
    -in travis/libraries-key.asc.enc -out travis/libraries-key.asc -d
  - gpg --import travis/libraries-key.asc
  - sh travis/copy_maven_settings.sh
after_success:
  - mvn jacoco:report coveralls:report
  - bash <(curl -s https://codecov.io/bash)
